### ISSUE TITLE
Пароли в гите

### ISSUE THREAD

**Issue by SmartPhoneJava** [go-park-mail-ru/2019_2_LeMMaS#33]
https://github.com/go-park-mail-ru/2019_2_LeMMaS/blob/de68b0b6ca1dfb45590e371ef5585cf9ce015686/docker/docker-compose.yml#L38

Нехорошо хранить пароли в открытом доступе. Используйте [секреты](https://docs.docker.com/engine/swarm/secrets/), чтобы передать в контейнер скрипт, создающий пользователя БД. Сам скрипт добавляете в гитигнор, как вы сделали с .env и готово, ваши секреты надежно спрятаны :) [Пример](https://ilhicas.com/2019/01/26/Using-docker-secrets-postgres.html).

**Comment by kzon** [comment]
Не вижу тут проблемы. Это пароль для локальной разработки, на проде пароль берётся из env файла.

**Comment by SmartPhoneJava** [comment]
Извиняюсь, привел ссылку не на ту строчку. Речь про вот эту - https://github.com/go-park-mail-ru/2019_2_LeMMaS/blob/de68b0b6ca1dfb45590e371ef5585cf9ce015686/docker/docker-compose.yml#L56-L58

Если у вас в проде есть создание в БД пользователя с другим именем/паролем, то вопросов не имею.
