### ISSUE TITLE
Захордкоженный конфиг

### ISSUE THREAD

**Issue by SmartPhoneJava** [go-park-mail-ru/2019_2_LeMMaS#34]
https://github.com/go-park-mail-ru/2019_2_LeMMaS/blob/de68b0b6ca1dfb45590e371ef5585cf9ce015686/pkg/service/api/delivery/const.go#L31
Эти данные(SessionCookieName и SessionCookieExpire) должны передаваться через файл конфигурации

**Comment by kzon** [comment]
Почему? Ведь нет потребности менять их часто

**Comment by SmartPhoneJava** [comment]
Согласен)
